/*
Group By, Order By
*/

SELECT GENDER
FROM EMPLOYEEDEMOGRAPHICS
GROUP BY GENDER

SELECT GENDER , COUNT(GENDER) AS COUNT
FROM EMPLOYEEDEMOGRAPHICS
GROUP BY GENDER

SELECT GENDER ,AGE, COUNT(GENDER) AS COUNT
FROM EMPLOYEEDEMOGRAPHICS
GROUP BY GENDER,AGE

SELECT GENDER ,AGE, COUNT(GENDER) AS COUNT
FROM EMPLOYEEDEMOGRAPHICS
WHERE AGE > 31
GROUP BY GENDER,AGE

SELECT GENDER , COUNT(GENDER) AS COUNTGENDER
FROM EMPLOYEEDEMOGRAPHICS
WHERE AGE > 31
GROUP BY GENDER
ORDER BY COUNTGENDER DESC

SELECT *
FROM EMPLOYEEDEMOGRAPHICS
ORDER BY AGE DESC ,GENDER DESC

SELECT * 
FROM EMPLOYEEDEMOGRAPHICS
ORDER BY 4 DESC , 5 DESC