/*
Having Clause
*/

SELECT JOBTITLE, COUNT(JOBTITLE) AS COUNT
FROM SQLTutorial.dbo.EMPLOYEEDEMOGRAPHICS
JOIN SQLTutorial.DBO.EMPLOYEESALARY
on EMPLOYEEDEMOGRAPHICS.EMPLOYEID  = EMPLOYEESALARY.EMPLOYEEID
GROUP BY JOBTITLE
HAVING COUNT(JOBTITLE) > 1

SELECT JOBTITLE, AVG(SALARY) AS AVERAGE_SALARY
FROM SQLTutorial.dbo.EMPLOYEEDEMOGRAPHICS
JOIN SQLTutorial.DBO.EMPLOYEESALARY
on EMPLOYEEDEMOGRAPHICS.EMPLOYEID  = EMPLOYEESALARY.EMPLOYEEID
GROUP BY JOBTITLE
ORDER BY AVERAGE_SALARY

SELECT JOBTITLE, AVG(SALARY) AS AVERAGE_SALARY
FROM SQLTutorial.dbo.EMPLOYEEDEMOGRAPHICS
JOIN SQLTutorial.DBO.EMPLOYEESALARY
on EMPLOYEEDEMOGRAPHICS.EMPLOYEID  = EMPLOYEESALARY.EMPLOYEEID
GROUP BY JOBTITLE
HAVING AVG(SALARY) > 45000
ORDER BY AVERAGE_SALARY
