/*
Inner Joins, Full/Left/Right/Outer Joins
*/

SELECT *
FROM SQLTutorial.dbo.EMPLOYEEDEMOGRAPHICS

SELECT *
FROM SQLTutorial.dbo.EMPLOYEESALARY

--INNER JOIN
SELECT *
FROM SQLTutorial.DBO.EMPLOYEEDEMOGRAPHICS
INNER JOIN SQLTutorial.dbo.EMPLOYEESALARY
ON EMPLOYEEDEMOGRAPHICS.EMPLOYEID = EMPLOYEESALARY.EMPLOYEEID

-- FULL OUTER
SELECT *
FROM SQLTutorial.DBO.EMPLOYEEDEMOGRAPHICS
FULL OUTER JOIN SQLTutorial.dbo.EMPLOYEESALARY
ON EMPLOYEEDEMOGRAPHICS.EMPLOYEID = EMPLOYEESALARY.EMPLOYEEID

-- LEFT OUTER JOIN
SELECT *
FROM SQLTutorial.DBO.EMPLOYEEDEMOGRAPHICS
LEFT OUTER JOIN SQLTutorial.dbo.EMPLOYEESALARY
ON EMPLOYEEDEMOGRAPHICS.EMPLOYEID = EMPLOYEESALARY.EMPLOYEEID

SELECT *
FROM SQLTutorial.DBO.EMPLOYEEDEMOGRAPHICS
RIGHT OUTER JOIN SQLTutorial.dbo.EMPLOYEESALARY
ON EMPLOYEEDEMOGRAPHICS.EMPLOYEID = EMPLOYEESALARY.EMPLOYEEID

SELECT EMPLOYEEDEMOGRAPHICS.EMPLOYEID,FIRSTNAME,LASTNAME, JOBTITLE,SALARY
FROM SQLTutorial.DBO.EMPLOYEEDEMOGRAPHICS
INNER JOIN SQLTutorial.dbo.EMPLOYEESALARY
ON EMPLOYEEDEMOGRAPHICS.EMPLOYEID = EMPLOYEESALARY.EMPLOYEEID

SELECT *
FROM SQLTutorial.DBO.EMPLOYEEDEMOGRAPHICS
FULL OUTER JOIN SQLTutorial.dbo.EMPLOYEESALARY
ON EMPLOYEEDEMOGRAPHICS.EMPLOYEID = EMPLOYEESALARY.EMPLOYEEID

SELECT EMPLOYEEDEMOGRAPHICS.EMPLOYEID,FIRSTNAME,LASTNAME,SALARY
FROM SQLTutorial.DBO.EMPLOYEEDEMOGRAPHICS
INNER JOIN SQLTutorial.dbo.EMPLOYEESALARY
ON EMPLOYEEDEMOGRAPHICS.EMPLOYEID = EMPLOYEESALARY.EMPLOYEEID
WHERE FIRSTNAME <> 'Michael'
ORDER BY SALARY DESC

SELECT JOBTITLE,AVG(SALARY)
FROM SQLTutorial.dbo.EMPLOYEEDEMOGRAPHICS
INNER JOIN SQLTutorial.dbo.EMPLOYEESALARY
ON EMPLOYEEDEMOGRAPHICS.EMPLOYEID = EMPLOYEESALARY.EMPLOYEEID
WHERE JOBTITLE = 'Salesman'
GROUP BY JOBTITLE
