/*
partition by
*/


SELECT DEM.FIRSTNAME, DEM.LASTNAME,DEM.GENDER,SAL.SALARY,
COUNT(DEM.GENDER) OVER (PARTITION BY DEM.GENDER) AS TotalGender
FROM SQltUTORIAL.DBO.EMPLOYEEDEMOGRAPHICS DEM
JOIN SQLTutorial.dbo.EMPLOYEESALARY SAL
 ON DEM.EMPLOYEID = SAL.EMPLOYEEID
 

 SELECT GENDER, COUNT(GENDER)
 FROM SQLTutorial.dbo.EMPLOYEEDEMOGRAPHICS DEM
 JOIN SQLTutorial.DBO.EMPLOYEESALARY SAL
 ON DEM.EMPLOYEID = SAL.EMPLOYEEID
 GROUP BY GENDER