SELECT DISTINCT(GENDER) FROM EMPLOYEEDEMOGRAPHICS

SELECT COUNT(LASTNAME) AS LASTNAMECOUNT FROM EMPLOYEEDEMOGRAPHICS;

SELECT MAX(SALARY) FROM EMPLOYEESALARY
SELECT AVG(SALARY) FROM EMPLOYEESALARY
SELECT MIN(SALARY) FROM EMPLOYEESALARY

SELECT * FROM SQLTutorial.dbo.EMPLOYEESALARY

