/*

Subqueries (in the select, from , and where statement)

*/


SELECT *
FROM EMPLOYEESALARY

--SUB QUERY IN SELECT STATEMENT

SELECT EMPLOYEEID,SALARY, (SELECT AVG(SALARY) FROM EMPLOYEESALARY) AS ALLAVGSALARY
FROM EMPLOYEESALARY


SELECT EMPLOYEEID,SALARY, AVG(SALARY) OVER() AS ALLAVGSALARY
FROM EMPLOYEESALARY

SELECT EMPLOYEEID,SALARY, AVG(SALARY) AS ALLAVGSALARY
FROM EMPLOYEESALARY
GROUP BY EMPLOYEEID, SALARY
ORDER BY 1,2


SELECT a.EMPLOYEEID, ALLAVGSALARY
FROM 
(SELECT EMPLOYEEID,SALARY, AVG(SALARY) OVER() AS ALLAVGSALARY 
 FROM EMPLOYEESALARY) a


SELECT EMPLOYEEID,JOBTITLE ,SALARY 
FROM EMPLOYEESALARY
WHERE EMPLOYEEID IN (
SELECT EMPLOYEEID FROM EMPLOYEEDEMOGRAPHICS WHERE AGE > 30)