/*
Union , Union All
*/

-- UNION WILL REMOVE DUPLICATES
SELECT * 
FROM EMPLOYEEDEMOGRAPHICS
UNION
SELECT *
FROM WareHouseEmployeeDemographics

-- UNION ALL WILL KEEP DUPLICATES
SELECT * 
FROM EMPLOYEEDEMOGRAPHICS
UNION ALL
SELECT *
FROM WareHouseEmployeeDemographics



SELECT EmployeeID,FirstName,Age
FROM SQLTUTORIAL.DBO.WareHouseEmployeeDemographics
UNION
SELECT EMPLOYEEID,JOBTITLE,SALARY
FROM SQLTUTORIAL.DBO.EMPLOYEESALARY
ORDER BY EmployeeID