/*
WHERE STATEMENT
=,<>,<,>,And,Or,Like,Null,Not Null, In
*/

SELECT *
FROM EMPLOYEEDEMOGRAPHICS
WHERE AGE >= 30

SELECT *
FROM EMPLOYEEDEMOGRAPHICS
WHERE AGE <= 32 AND GENDER = 'Male'

SELECT *
FROM EMPLOYEEDEMOGRAPHICS
WHERE LASTNAME LIKE '%S%'

SELECT *
FROM EMPLOYEEDEMOGRAPHICS
WHERE FIRSTNAME IS NOT NULL

SELECT *
FROM EMPLOYEEDEMOGRAPHICS
WHERE FIRSTNAME IN ('Jim','Michael')

